export const ITEM_SELECTED = 'ITEM_SELECTED';
export const GET_ALL_PRODUCTS='GET_ALL_PRODUCTS';
export const UPDATED_CART='UPDATED_CART';
export const ADD_TO_CART='ADD_TO_CART';
export const INCREMENT_PRODUCT='INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT='DECREMENT_PRODUCT';
export const OUT_PRODUCT='OUT_PRODUCT'; 
export const NEW_ORDER='NEW_ORDER';